getrebuild/rebuild

pom.xml, src/main/java/com/rebuild/server/helper/BlackList.java, src/main/java/com/rebuild/server/helper/QiniuCloud.java, src/main/java/com/rebuild/server/helper/SMSender.java, src/main/java/com/rebuild/server/helper/SystemConfig.java, src/main/java/com/rebuild/server/service/bizz/privileges/SecurityManager.java, src/main/java/com/rebuild/web/admin/bizz/LoginLogControll.java, src/main/java/com/rebuild/web/admin/entityhub/MetaFieldControll.java, src/main/java/com/rebuild/web/base/entity/GeneralRecordOperatorControll.java, src/main/webapp/assets/css/view-page.css, src/main/webapp/assets/js/rb-view.jsx, src/test/java/com/rebuild/server/business/charts/ChartsTest.java, src/test/java/com/rebuild/server/business/series/SeriesGeneratorTest.java, src/test/java/com/rebuild/server/helper/BlackListTest.java, src/test/java/com/rebuild/server/helper/QiniuCloudTest.java, src/test/java/com/rebuild/server/helper/SMSenderTest.java, src/test/java/com/rebuild/server/helper/SystemConfigTest.java, src/test/java/com/rebuild/server/helper/VCodeTest.java, src/test/java/com/rebuild/server/helper/manager/AdvFilterManagerTest.java, src/test/java/com/rebuild/server/helper/manager/DashboardManagerTest.java, src/test/java/com/rebuild/server/helper/manager/NavManagerTest.java, src/test/java/com/rebuild/server/helper/manager/PickListManagerTest.java, src/test/java/com/rebuild/web/MvcTestSupport.java, src/test/java/com/rebuild/web/admin/entityhub/FormDesignControllTest.java, src/test/java/com/rebuild/web/admin/entityhub/MetaEntityControllTest.java, src/test/java/com/rebuild/web/admin/entityhub/MetaFieldControllTest.java, src/test/java/com/rebuild/web/base/entity/GeneralRecordOperatorControllTest.java, src/test/java/com/rebuild/web/base/entity/ReferenceSearchTest.java, src/test/java/com/rebuild/web/base/entity/RelatedListControllTest.java
Eclipse coverage 50%+, codecov 40%+
=> Makeup testcases

pom.xml, src/main/java/com/rebuild/server/helper/SMSender.java, src/main/java/com/rebuild/server/helper/SystemConfig.java, src/main/resources/locales/mail-notify.html
=> Mail notify template

src/main/java/com/rebuild/server/Application.java, src/main/java/com/rebuild/server/metadata/EntityHelper.java, src/main/java/com/rebuild/server/metadata/MetadataHelper.java, src/main/java/com/rebuild/server/metadata/MetadataSorter.java, src/main/java/com/rebuild/server/portals/DataListManager.java, src/main/java/com/rebuild/server/portals/datalist/JSONQueryParser.java, src/main/java/com/rebuild/web/base/entity/DataListSettingsControll.java, src/main/java/com/rebuild/web/base/entity/ReferenceSearch.java, src/main/java/com/rebuild/web/user/signin/LoginControll.java, src/main/java/com/rebuild/web/user/signin/SignUpControll.java, src/main/webapp/assets/css/dashboard.css, src/main/webapp/assets/css/rb-base.css, src/main/webapp/user/login.jsp
=> #RB-109 datalist can show ref-fields

src/main/java/com/rebuild/server/business/dataio/DataImporter.java, src/main/java/com/rebuild/server/portals/DataListManager.java, src/main/java/com/rebuild/server/service/base/GeneralEntityService.java, src/main/java/com/rebuild/server/service/base/QuickCodeReindexTask.java, src/main/java/com/rebuild/web/admin/entityhub/ClassificationControll.java, src/main/java/com/rebuild/web/base/entity/ClassificationSearch.java, src/main/java/com/rebuild/web/base/entity/DataListSettingsControll.java, src/main/java/com/rebuild/web/base/entity/GeneralEntityOperatorControll.java, src/main/java/com/rebuild/web/base/entity/GeneralEntityRecordControll.java, src/main/java/com/rebuild/web/base/entity/ReferenceSearch.java, src/main/java/com/rebuild/web/user/signin/LoginControll.java, src/main/webapp/admin/bizuser/user-list.jsp, src/main/webapp/assets/css/rb-page.css, src/main/webapp/assets/css/view-page.css, src/main/webapp/assets/js/assign-share.jsx, src/main/webapp/assets/js/rb-forms.jsx, src/main/webapp/assets/js/rb-list.jsx, src/main/webapp/assets/js/rb-view.jsx, src/main/webapp/general-entity/record-list.jsp, src/main/webapp/general-entity/record-view.jsp, src/test/java/com/rebuild/server/helper/task/QuickCodeReindexTaskTest.java, src/test/java/com/rebuild/web/base/entity/GeneralEntityRecordControllTest.java
=> #RB-104 Batch unshared

.eslintrc.json, src/main/java/com/rebuild/server/service/query/AdvFilterParser.java, src/main/webapp/admin/bizuser/dept-list.jsp, src/main/webapp/admin/bizuser/login-logs.jsp, src/main/webapp/admin/bizuser/user-list.jsp, src/main/webapp/admin/entityhub/fields.jsp, src/main/webapp/assets/js/rb-datalist.jsx, src/main/webapp/assets/js/rb-view.jsx, src/main/webapp/general-entity/record-list.jsp, src/main/webapp/general-entity/slave-list.jsp
And renamed rb-list.jsx > rb-datalist.jsx
=> #RB-108 feat:列表快速搜索组件可指定搜索字段

src/main/java/com/rebuild/server/configuration/portals/FormsBuilder.java, src/main/webapp/assets/css/form-design.css, src/main/webapp/assets/css/rb-page.css, src/main/webapp/assets/js/entity/form-design.jsx, src/main/webapp/assets/js/rb-datalist.jsx, src/main/webapp/assets/js/rb-forms.jsx
=> RB-486 Form input tips 

src/main/java/com/rebuild/server/helper/ConfigurableItem.java, src/main/java/com/rebuild/server/helper/setup/DatabaseBackup.java, src/main/java/com/rebuild/server/service/PerHourJob.java, src/main/java/com/rebuild/server/service/query/AdvFilterParser.java, src/main/java/com/rebuild/utils/CommonsUtils.java, src/main/java/com/rebuild/utils/MaxBackupIndexDailyRollingFileAppender.java, src/main/java/com/rebuild/web/admin/SysConfigurationControll.java, src/main/resources/application-job.xml, src/main/webapp/admin/system-general.jsp, src/main/webapp/assets/css/rb-base.css, src/main/webapp/assets/css/rb-page.css, src/main/webapp/assets/js/entityhub/recycle-bin.jsx, src/main/webapp/assets/js/entityhub/revision-history.jsx, src/main/webapp/assets/js/rb-datalist.jsx, src/main/webapp/assets/js/rb-page.js, src/test/java/com/rebuild/server/helper/setup/DatabaseBackupTest.java, src/test/java/com/rebuild/utils/JSONUtilsTest.java, src/test/java/com/rebuild/utils/RbCodecTest.java
=> RB-526 Auto backup 

src/main/java/com/rebuild/server/business/feeds/FeedsScheduleJob.java, src/main/java/com/rebuild/server/business/trigger/impl/SendNotification.java, src/main/java/com/rebuild/server/helper/SMSender.java, src/main/java/com/rebuild/server/service/bizz/privileges/User.java, src/main/java/com/rebuild/server/service/bizz/privileges/UserStore.java, src/main/java/com/rebuild/web/feeds/FeedsListControll.java, src/main/resources/locales/email_zh-CN.html, src/main/resources/metadata-conf.xml, src/main/resources/scripts/db-init.sql, src/main/resources/scripts/db-upgrade.sql, src/main/webapp/account/settings.jsp, src/main/webapp/assets/js/feeds/feeds-list.jsx, src/main/webapp/assets/js/feeds/feeds-post.jsx, src/main/webapp/assets/js/triggers/trigger.SENDNOTIFICATION.jsx, src/main/webapp/assets/js/user-settings.jsx, src/main/webapp/feeds/home.jsp
- trigger: SENDNOTIFICATION
- Feeds: FeedsSchedule
- User add field `workphone`
=> Mobile supports

src/main/java/com/rebuild/server/helper/datalist/ProtocolFilterParser.java, src/main/java/com/rebuild/web/base/UsersGetting.java, src/main/webapp/assets/css/charts.css, src/main/webapp/assets/css/dashboard.css, src/main/webapp/assets/css/rb-page.css, src/main/webapp/assets/js/charts/charts.jsx, src/main/webapp/assets/js/charts/dashboard.jsx, src/main/webapp/assets/js/rb-components.jsx, src/main/webapp/assets/js/rb-datalist.jsx, src/main/webapp/dashboard/chart-design.jsp, src/main/webapp/dashboard/home.jsp
1. Fullscreen
2. Legend for chart
3. Auto-refresh dashboard
=> RB-584 More charts controls

pom.xml, src/main/java/com/rebuild/server/Application.java, src/main/java/com/rebuild/server/business/trigger/impl/AutoAssign.java, src/main/java/com/rebuild/server/business/trigger/impl/AutoShare.java, src/main/java/com/rebuild/server/helper/DistributedJobBean.java, src/main/java/com/rebuild/server/helper/cache/RecordOwningCache.java, src/main/java/com/rebuild/server/service/bizz/UserHelper.java, src/main/java/com/rebuild/server/service/bizz/privileges/PrivilegesGuardInterceptor.java, src/main/resources/application-job.xml, src/main/resources/application.properties, src/main/resources/jdbc.properties, src/test/java/com/rebuild/server/service/bizz/UserHelperTest.java
=> Fix v1.10.1

pom.xml, src/main/java/com/rebuild/server/Application.java, src/main/java/com/rebuild/server/business/trigger/impl/TriggerByTimerJob.java, src/main/java/com/rebuild/server/helper/AesPreferencesConfigurer.java, src/main/java/com/rebuild/server/service/bizz/privileges/Department.java, src/main/java/com/rebuild/server/service/bizz/privileges/PrivilegesManager.java, src/main/webapp/assets/js/entityhub/field-edit.jsx
1. Feeds in view tab
2. TriggerByTimerJob run
=> Fixs v1.11.1

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyFile.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyMultiSelect.java, src/main/java/com/rebuild/core/service/files/AttachmentAwareObserver.java, src/main/java/com/rebuild/core/service/query/AdvFilterParser.java
=> fix: 2.3.1

src/main/java/com/rebuild/core/service/approval/ApprovalHelper.java, src/main/java/com/rebuild/core/service/approval/FlowBranch.java, src/main/java/com/rebuild/core/service/approval/FlowNode.java, src/main/java/com/rebuild/core/service/approval/RobotApprovalManager.java, src/main/java/com/rebuild/core/service/query/AdvFilterParser.java, src/main/java/com/rebuild/core/service/query/ParseHelper.java, src/main/java/com/rebuild/core/service/query/QueryHelper.java, src/main/java/com/rebuild/core/service/trigger/RobotTriggerManager.java, src/main/java/com/rebuild/web/robot/approval/ApprovalAdminController.java, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/admin/approval-design.js, src/main/resources/web/assets/js/rb-advfilter.js, src/main/resources/web/assets/js/rb-approval.js
=> Approval filter 721 723

src/main/java/com/rebuild/core/metadata/EntityHelper.java, src/main/java/com/rebuild/core/metadata/MetadataHelper.java, src/main/java/com/rebuild/core/metadata/impl/Entity2Schema.java, src/main/java/com/rebuild/core/metadata/impl/Field2Schema.java, src/main/java/com/rebuild/core/service/approval/ApprovalFields2Schema.java, src/main/java/com/rebuild/core/service/approval/ApprovalProcessor.java, src/main/java/com/rebuild/core/service/approval/ApprovalStepService.java, src/main/java/com/rebuild/core/service/general/EntityService.java, src/main/java/com/rebuild/core/service/general/GeneralEntityService.java, src/main/java/com/rebuild/web/general/ReferenceSearchController.java, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/rb-approval.js, src/main/resources/web/assets/js/rb-datalist.common.js, src/main/resources/web/assets/js/rb-view.js
=> Last approver RB-732

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/BootEnvironmentPostProcessor.java, src/main/java/com/rebuild/core/service/trigger/impl/GroupAggregation.java, src/main/java/com/rebuild/core/support/setup/Installer.java, src/main/java/com/rebuild/web/commons/FileDownloader.java, src/main/resources/application-dev.yml, src/main/resources/web/assets/js/admin/data-imports.js, src/main/resources/web/assets/js/project/project-tasks.js
=> bugfix 2.6.1

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/support/ConfigurationItem.java, src/main/java/com/rebuild/utils/CommonsUtils.java, src/main/java/com/rebuild/web/RebuildWebConfigurer.java, src/main/java/com/rebuild/web/RebuildWebInterceptor.java, src/main/java/com/rebuild/web/admin/ConfigurationController.java, src/main/java/com/rebuild/web/commons/FileDownloader.java, src/main/java/com/rebuild/web/user/signup/LoginController.java, src/main/resources/scripts/db-init.sql, src/main/resources/web/admin/system-cfg.html, src/main/resources/web/assets/css/rb-base.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/admin/syscfg-g.js, src/main/resources/web/assets/js/admin/syscfg.js, src/main/resources/web/assets/js/rb-base.js, src/main/resources/web/assets/js/rb-components.js, src/main/resources/web/assets/js/rb-datalist.js, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/error/error.html, src/main/resources/web/signup/login.html
=> View show topbar 743

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/ServerStatus.java, src/main/java/com/rebuild/core/service/trigger/impl/FieldWriteback.java, src/main/java/com/rebuild/web/robot/trigger/FieldAggregationController.java, src/main/java/com/rebuild/web/robot/trigger/FieldWritebackController.java, src/main/resources/web/assets/js/rb-forms.append.js, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/assets/js/trigger/trigger.FIELDWRITEBACK.js
1. Writeback of trigger supports `one2one` mode
2. Map location
=> Field writeback one2one

src/main/java/com/rebuild/core/configuration/general/FormsBuilder.java, src/main/java/com/rebuild/web/general/RelatedListController.java, src/main/resources/web/assets/css/charts.css, src/main/resources/web/assets/css/files.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/css/view-page.css, src/main/resources/web/assets/js/rb-view.append.js, src/main/resources/web/assets/js/rb-view.js
1. Edit on related list
2. Fix approval state for details
=> Reletaed update

pom.xml, src/main/java/com/rebuild/web/commons/FileDownloader.java, src/main/java/com/rebuild/web/commons/UseThemeController.java, src/main/resources/web/_include/header.html, src/main/resources/web/admin/system-cfg.html, src/main/resources/web/assets/js/admin/syscfg-g.js, src/main/resources/web/signup/login.html
=> Free theme 799

src/main/java/com/rebuild/web/general/CommonOperatingController.java, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/assets/js/rb-forms.protable.js
1. feat: form modal maximize
2. better: protable widths
=> Forms window resize

.eslintrc.js, src/main/java/com/rebuild/core/service/query/AdvFilterParser.java, src/main/java/com/rebuild/core/service/query/FilterRecordChecker.java, src/main/java/com/rebuild/core/service/query/QueryHelper.java, src/main/java/com/rebuild/core/service/trigger/RobotTriggerManager.java, src/main/java/com/rebuild/core/support/general/QueryParser.java, src/main/resources/web/admin/metadata/fields.html, src/main/resources/web/assets/js/admin/transform-editor.js, src/main/resources/web/assets/js/charts/chart-design.js, src/main/resources/web/assets/js/rb-advfilter.js, src/main/resources/web/assets/js/rb-datalist.common.js, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/assets/js/rb-page.js, src/main/resources/web/general/show-fields.html
1. AdvFilter support field-var
2. $isSysMask
=> Advfilter use record

src/main/java/com/rebuild/core/ServerStatus.java, src/main/java/com/rebuild/core/configuration/general/BaseLayoutManager.java, src/main/java/com/rebuild/core/configuration/general/DataListManager.java, src/main/java/com/rebuild/core/configuration/general/ShareToManager.java, src/main/java/com/rebuild/core/configuration/general/ViewAddonsManager.java, src/main/java/com/rebuild/web/admin/metadata/ViewAddonsController.java, src/main/java/com/rebuild/web/configuration/ListFieldsController.java, src/main/java/com/rebuild/web/general/ReferenceSearchController.java, src/main/java/com/rebuild/web/general/RelatedListController.java, src/main/resources/web/admin/bizuser/dept-view.html, src/main/resources/web/admin/bizuser/role-view.html, src/main/resources/web/admin/bizuser/team-view.html, src/main/resources/web/admin/bizuser/user-view.html, src/main/resources/web/admin/metadata/field-edit.html, src/main/resources/web/admin/metadata/form-design.html, src/main/resources/web/admin/system-cfg.html, src/main/resources/web/assets/js/metadata/field-edit.js, src/main/resources/web/assets/js/rb-forms.append.js, src/main/resources/web/assets/js/rb-view.js, src/main/resources/web/assets/js/rebuild-tour.js, src/main/resources/web/general/detail-view.html, src/main/resources/web/general/print-preview.html, src/main/resources/web/general/record-view.html
=> Showfields spec

src/main/java/com/rebuild/core/service/trigger/impl/SendNotification.java
=> Trigger async

src/main/java/com/rebuild/web/general/ListAndViewRedirection.java, src/main/resources/web/admin/metadata/list-filterpane.html, src/main/resources/web/assets/css/list-page.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/css/view-page.css, src/main/resources/web/assets/js/metadata/entity-advanced.js, src/main/resources/web/assets/js/metadata/list-filterpane.js, src/main/resources/web/assets/js/rb-advfilter.js, src/main/resources/web/assets/js/rb-datalist.common.js, src/main/resources/web/assets/js/rb-datalist.js, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/general/detail-list.html, src/main/resources/web/general/dock-form.html, src/main/resources/web/general/dock-view.html, src/main/resources/web/general/record-list.html
1. Filter pane open
2. Dock page for form/view
=> List styles

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/configuration/general/AutoFillinManager.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyPhone.java, src/main/java/com/rebuild/core/service/PerHourJob.java, src/main/java/com/rebuild/core/support/CommandArgs.java, src/main/java/com/rebuild/core/support/setup/DatabaseBackup.java, src/main/java/com/rebuild/core/support/task/TaskExecutors.java, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/css/triggers.css, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/assets/js/trigger/trigger-design.js
1. [优化] 时间选择器分钟间隔1分钟
2. [优化] 强制回填空值
3. [修复] 手机版新建时默认值不回填问题
=> Fix 3.3 beta1

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/privileges/UserStore.java, src/main/java/com/rebuild/core/privileges/bizz/CombinedRole.java, src/main/java/com/rebuild/core/privileges/bizz/CustomEntityPrivileges.java, src/main/java/com/rebuild/core/privileges/bizz/ZeroPrivileges.java, src/main/java/com/rebuild/core/service/PerHourJob.java, src/main/java/com/rebuild/core/support/KVStorage.java, src/main/java/com/rebuild/core/support/License.java, src/main/java/com/rebuild/core/support/RebuildConfiguration.java, src/main/java/com/rebuild/core/support/setup/DatabaseBackup.java, src/main/java/com/rebuild/core/support/setup/Installer.java, src/main/java/com/rebuild/core/support/task/TaskExecutors.java, src/main/java/com/rebuild/utils/MarkdownLinkAttrProvider.java, src/main/java/com/rebuild/utils/MarkdownUtils.java, src/main/java/com/rebuild/web/RebuildWebConfigurer.java, src/main/java/com/rebuild/web/admin/setup/InstallController.java, src/main/resources/web/admin/setup/install.html, src/main/resources/web/admin/system-cfg.html, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/admin/setup-install.js, src/main/resources/web/assets/js/rb-assignshare.js, src/main/resources/web/assets/js/rb-forms.append.js
1. [修复] 多角色合并丢失自定义权限
2. [优化] 安装时可输入商业授权码
3. [优化] 记录操作提示
4. [优化] 安装时可填写商业授权码
=> Fix 3.3 beta2

pom.xml, src/main/java/com/rebuild/core/configuration/general/FormsBuilder.java, src/main/java/com/rebuild/core/privileges/UserFilters.java, src/main/java/com/rebuild/core/support/general/DataListBuilderImpl.java, src/main/java/com/rebuild/web/EntityController.java, src/main/java/com/rebuild/web/admin/bizz/BizzPageView.java, src/main/java/com/rebuild/web/admin/metadata/MetaEntityController.java, src/main/java/com/rebuild/web/commons/UsersGetting.java, src/main/java/com/rebuild/web/feeds/FeedsGroupController.java, src/main/java/com/rebuild/web/general/GeneralListController.java, src/main/java/com/rebuild/web/general/GeneralModelController.java, src/main/java/com/rebuild/web/general/ReferenceSearchController.java, src/main/resources/web/assets/js/rb-datalist.common.js
=> Be enable bizz part

pom.xml, src/main/java/com/rebuild/core/configuration/general/FormsBuilder.java, src/main/java/com/rebuild/core/service/dataimport/DataImporter.java, src/main/java/com/rebuild/core/service/dataimport/ImportRule.java, src/main/java/com/rebuild/core/service/general/GeneralEntityService.java, src/main/java/com/rebuild/core/service/trigger/impl/SendNotification.java, src/main/java/com/rebuild/core/support/ConfigurationItem.java, src/main/java/com/rebuild/core/support/general/ContentWithFieldVars.java, src/main/java/com/rebuild/utils/CommonsUtils.java, src/main/java/com/rebuild/utils/OshiUtils.java, src/main/java/com/rebuild/web/KnownExceptionConverter.java, src/main/java/com/rebuild/web/commons/FileDownloader.java, src/main/resources/web/admin/data/data-imports-body.html, src/main/resources/web/admin/metadata/form-design.html, src/main/resources/web/assets/css/form-design.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/css/view-page.css, src/main/resources/web/assets/js/admin/data-imports.js, src/main/resources/web/assets/js/metadata/field-formula.js, src/main/resources/web/assets/js/metadata/form-design.js, src/main/resources/web/assets/js/rb-datalist.js, src/main/resources/web/assets/js/rb-forms.js, src/main/resources/web/assets/js/rb-view.js, src/main/resources/web/assets/js/trigger/trigger-design.js, src/main/resources/web/assets/js/trigger/trigger.FIELDWRITEBACK.js, src/main/resources/web/assets/js/trigger/trigger.SENDNOTIFICATION.js, src/main/resources/web/general/detail-view.html, src/main/resources/web/general/record-view.html, src/test/java/com/rebuild/TestSupport.java, src/test/java/com/rebuild/web/BaseControllerTest.java
=> Share assign n 90

src/main/java/com/rebuild/core/privileges/ChangeOwningDeptTask.java, src/main/java/com/rebuild/core/privileges/UserImporter.java, src/main/java/com/rebuild/core/rbstore/ClassificationFileImporter.java, src/main/java/com/rebuild/core/service/dataimport/DataImporter.java, src/main/java/com/rebuild/core/service/general/BulkAssign.java, src/main/java/com/rebuild/core/service/general/BulkBatchUpdate.java, src/main/java/com/rebuild/core/service/general/BulkDelete.java, src/main/java/com/rebuild/core/service/general/BulkShare.java, src/main/java/com/rebuild/core/service/general/BulkUnshare.java, src/main/java/com/rebuild/core/service/general/QuickCodeReindexTask.java, src/main/java/com/rebuild/core/service/general/SeriesReindexTask.java, src/main/java/com/rebuild/core/support/CommandArgs.java, src/main/java/com/rebuild/core/support/task/HeavyTask.java, src/main/java/com/rebuild/core/support/task/TaskExecutors.java, src/main/java/com/rebuild/web/commons/HeavyTaskController.java, src/main/resources/web/assets/js/admin/data-imports.js, src/main/resources/web/assets/js/charts/chart-design.js, src/main/resources/web/assets/js/general/rb-datalist.common.js, src/main/resources/web/assets/js/general/rb-forms.append.js, src/main/resources/web/assets/js/metadata/classification-editor.js, src/main/resources/web/assets/js/rb-components.js, src/main/resources/web/assets/js/rb-page.js, src/main/resources/web/assets/js/trigger/trigger-design.js, src/test/java/com/rebuild/core/support/task/HeavyTaskTest.java
1. Cancel Batch update/approve
2. init UniPush
3. be: isInterruptState
=> Cancel bulk 107

src/main/java/com/rebuild/core/metadata/impl/Field2Schema.java, src/main/java/com/rebuild/core/service/trigger/aviator/AviatorUtils.java, src/main/java/com/rebuild/core/service/trigger/aviator/OverOperatorType.java, src/main/java/com/rebuild/core/support/ConfigurationItem.java, src/main/java/com/rebuild/core/support/RebuildConfiguration.java, src/main/java/com/rebuild/core/support/integration/SMSender.java, src/main/java/com/rebuild/web/admin/ConfigurationController.java, src/main/resources/web/admin/integration/submail.html, src/main/resources/web/admin/metadata/field-edit.html, src/main/resources/web/assets/js/charts/dashboard.js, src/main/resources/web/assets/js/metadata/field-edit.js, src/main/resources/web/assets/js/rb-components.js, src/main/resources/web/assets/js/trigger/trigger.FIELDWRITEBACK.js, src/test/java/com/rebuild/core/service/trigger/aviator/AviatorUtilsTest.java
=> feat: Type cast 

pom.xml, src/main/java/com/rebuild/core/service/datareport/DataReportManager.java, src/main/java/com/rebuild/core/service/datareport/EasyExcelGenerator.java, src/main/java/com/rebuild/core/service/datareport/EasyExcelGenerator33.java, src/main/java/com/rebuild/core/service/datareport/EasyExcelListGenerator.java, src/main/java/com/rebuild/core/service/datareport/TemplateExtractor33.java, src/main/java/com/rebuild/core/service/datareport/TemplateFile.java, src/main/java/com/rebuild/core/service/files/FilesHelper.java, src/main/java/com/rebuild/core/service/trigger/ActionType.java, src/main/java/com/rebuild/core/service/trigger/TriggerResult.java, src/main/java/com/rebuild/core/service/trigger/impl/FieldAggregation.java, src/main/java/com/rebuild/core/service/trigger/impl/FieldWriteback.java, src/main/java/com/rebuild/core/support/SysbaseSupport.java, src/main/java/com/rebuild/utils/PdfConverter.java, src/main/java/com/rebuild/web/admin/data/ReportTemplateController.java, src/main/resources/web/admin/integration/dingtalk.html, src/main/resources/web/assets/css/triggers.css, src/main/resources/web/assets/js/general/print-preview.js, src/main/resources/web/assets/js/metadata/entity-new2.js, src/main/resources/web/assets/js/rb-page.js, src/main/resources/web/assets/js/trigger/trigger-design.js, src/main/resources/web/assets/js/trigger/trigger-list.js, src/main/resources/web/assets/js/trigger/trigger.FIELDAGGREGATION.js, src/main/resources/web/assets/js/trigger/trigger.FIELDWRITEBACK.js, src/main/resources/web/assets/js/trigger/trigger.GROUPAGGREGATION.js, src/main/resources/web/assets/js/trigger/trigger.SENDNOTIFICATION.js, src/test/java/com/rebuild/utils/ExcelUtilsTest.java
1. feat: AutoGenReport 
2. Shape in Excel
=> feat: AutoGenReport

src/main/java/com/rebuild/core/service/PerHourJob.java, src/main/java/com/rebuild/core/service/general/GeneralEntityService.java, src/main/java/com/rebuild/core/service/general/OperatingObserver.java, src/main/java/com/rebuild/core/service/trigger/RobotTriggerObserver.java, src/main/java/com/rebuild/web/project/ProjectController.java, src/main/java/com/rebuild/web/project/ProjectTaskController.java, src/main/resources/web/assets/css/chart-design.css, src/main/resources/web/assets/css/charts.css, src/main/resources/web/assets/css/project-tasks.css, src/main/resources/web/assets/js/admin/approval-design.js, src/main/resources/web/assets/js/project/project-tasks.js, src/main/resources/web/assets/js/project/task-view.js, src/main/resources/web/dashboard/chart-design.html, src/main/resources/web/project/project-tasks.html
=> feat: tasks list

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/service/approval/ApprovalProcessor.java, src/main/java/com/rebuild/core/service/query/AdvFilterParser.java, src/main/java/com/rebuild/web/commons/UsersGetting.java, src/main/java/com/rebuild/web/contacts/ContactsController.java, src/main/resources/web/assets/css/charts.css, src/main/resources/web/assets/css/list-page.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/admin/data-imports.js, src/main/resources/web/assets/js/general/rb-datalist.common.js, src/main/resources/web/assets/js/rb-components.js, src/main/resources/web/assets/js/rb-page.js
1. [修复] 详情页多地图显示问题
2. [修复] 外部表单分类字段填值问题
3. [修复] 项目任务详情XSS漏洞
4. [修复] 通讯录排序问题
5. [优化] 高级查询高级表达式兼容性
6. [优化] 若干页面样式
=> Fix 3.9 beta2

src/main/java/com/rebuild/core/service/dataimport/DataImporter.java, src/main/java/com/rebuild/core/service/trigger/impl/FieldWriteback.java, src/main/java/com/rebuild/web/admin/data/DataImportController.java, src/main/resources/web/assets/js/general/rb-view.js, src/main/resources/web/general/detail-view.html
1. [优化] 数据导入已存在记录支持更新所属用户
2. [优化] 多外部集成应用用户部门同步问题
3. [修复] 手机版钉钉位置定位
=> Fix 3.9 beta4

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/BootEnvironmentPostProcessor.java, src/main/java/com/rebuild/core/configuration/general/FormsBuilder.java, src/main/java/com/rebuild/core/service/query/QueryFactory.java, src/main/java/com/rebuild/core/support/OnlyOffice.java, src/main/java/com/rebuild/utils/CommonsUtils.java, src/main/java/com/rebuild/web/RebuildWebInterceptor.java, src/main/java/com/rebuild/web/commons/FileDownloader.java, src/main/java/com/rebuild/web/commons/FilePreviewer.java, src/main/java/com/rebuild/web/general/CommonOperatingController.java, src/main/java/com/rebuild/web/general/ModelExtrasController.java, src/main/java/com/rebuild/web/general/ReportsController.java, src/main/resources/web/assets/css/chat.css, src/main/resources/web/assets/css/rb-page.css, src/main/resources/web/assets/js/general/rb-datalist.common.js, src/main/resources/web/assets/js/general/rb-forms.append.js, src/main/resources/web/assets/js/rb-base.js, src/main/resources/web/assets/js/rb-components.js, src/main/resources/web/assets/js/rb-page.js, src/main/resources/web/common/shared-file.html, src/main/resources/web/general/print-preview.html, src/test/java/com/rebuild/utils/CommonsUtilsTest.java
- 修复长文本换行显示问题
- 修复自定义操作-记录直接转换问题
- 修复外部表单密码访问特殊符号密码问题
- 修复详情页默认打印空白页问题
- 优化文档预览服务兼容问题
- 优化外部表单页面验证过期问题
- 自定义操作可配置为预览模式
- 其他若干优化
=> Fix 4.1 beta2

pom.xml, src/main/java/com/rebuild/core/Application.java, src/main/java/com/rebuild/core/configuration/general/FormsBuilder.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyAnyReference.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyAvatar.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyField.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyFile.java, src/main/java/com/rebuild/core/metadata/easymeta/EasySign.java, src/main/java/com/rebuild/core/metadata/easymeta/EasyTag.java, src/main/java/com/rebuild/core/service/general/transform/RecordTransfomer37.java, src/main/java/com/rebuild/core/service/query/AdvFilterParser.java, src/main/java/com/rebuild/core/service/trigger/TriggerResult.java, src/main/java/com/rebuild/core/service/trigger/aviator/IsNullFunction.java, src/main/java/com/rebuild/web/RebuildWebConfigurer.java, src/main/java/com/rebuild/web/admin/AdminCli4.java, src/main/java/com/rebuild/web/admin/ConfigurationController.java, src/main/java/com/rebuild/web/general/CommonOperatingController.java, src/main/resources/web/_include/nav-top.html, src/main/resources/web/admin/metadata/field-edit.html, src/main/resources/web/assets/js/admin/config-comps.js, src/main/resources/web/assets/js/general/rb-datalist.common.js, src/main/resources/web/assets/js/general/rb-forms.js, src/main/resources/web/assets/js/general/rb-view.js, src/main/resources/web/general/record-view.html
1. 修复ISNULL函数问题
2. 修复记录转换明细问题
3. 修复明细默认显示/隐藏问题
4. 修复表单回填至任意引用无效问题
5. 其他若干优化
=> Fix 4.1 beta3
